#!/usr/bin/sh
# battery notification such awesome
# depends: acpi, notify-send
# license: GPLv3

# ========= DEFAULT SETTINGS =========

battery="/sys/class/power_supply/BAT0"
force=false
chargesafe=40
chargecrit=20

# otherwise cron-run script won't where to send
export DISPLAY=:0.0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

# ========= SETTING DERIVATIVES =========

status=`acpi | cut -d, -f1 | cut -d' ' -f3`
chargepercent=`acpi | cut -d, -f2 | tr -d ' %'`
remaining=`acpi | cut -d, -f3,4`

echo $status
echo $chargepercent

icondir="$HOME/.config/pixmaps"
if [ "$status" == "Charging" -o "$status" == "Full" ]; then
    icon="$icondir/battery-green.png"
else
    icon="$icondir/battery-orange.png"
fi
if [ $chargepercent -lt $chargecrit ]; then
    icon="$icondir/battery-red.png"
fi


# ========= FUNCTIONS =========
usage () {
    echo "TODO usage"
    exit 99
}

# ========= COMMANDLINE ARGS =========

while getopts f name
do
    case $name in
	f) force=true ;;
	?) usage ;;
    esac
done
shift `expr $OPTIND - 1`

# ========= PROGRAM =========

if [ x"$force" = x"true" -o $chargepercent -lt $chargesafe ]; then
    notify-send -i $icon "Power" " $status, $chargepercent%\n$remaining"
fi
